### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by mxstbr** [carteb/carte-blanche#11]
We need to give developers a few options to make it more customisable. Lets make a list:

# CarteBlanche Options

You can specify a few different options for this plugin:

- `componentRoot` (required): Folder where all of your component files are.

  ```JS
    plugins: [
      new CarteBlanche({
        componentRoot: 'src/components'
      })
    ]
  ```

- `dest` (default: `'styleguide/index.html'`): Change the location of the styleguide. Needs to be a HTML file.

  ```JS
    plugins: [
      new CarteBlanche({
        src: 'components/**/*.js',
        dest: 'mypath/index.html'
      })
    ]
  ```

- `plugins` (default: `ReactPlugin`): An array of plugins to use for this project

  ```JS
    var ReactPlugin = require('carte-blanche-plugin-react');
    var SourcePlugin = require('carte-blanche-plugin-source');

    plugins: [
      new CarteBlanche({
        src: 'components/**/*.js',
        plugins: [
         new SourcePlugin({ /* …options for the plugin here… */ }),
         new ReactPlugin()
        ]
      })
    ]
  ```

- `client`: Render the styleguide in your custom client. See [writing your own client](#) for more information.
  ```JS
  new CarteBlanche({
    src: 'bla',
    client: {
      script: './myNewClientBundle.js',
      styles: './myClientStyling.css'
    }
  })
  ```

- `filter` (default: matches uppercase files and uppercase folders with an index file): Regex that matches your components in the `componentRoot` folder. **We do not recommend changing this, as it quickly has unintended side effects.**

  ```JS
    plugins: [
      new CarteBlanche({
        filter: /.*\.jsx$/ // Matches all files ending in .jsx
      })
    ]
  ```

## ReactPlugin Options

- `variationFolderName` (default: `variations`): The name of the folders that stores the variation files.
  ```JS
  new ReactPlugin({
    variationFolderName: 'examples'
  })
  ```

- `port` (default: 8082): The port the variations server runs at.
  ```JS
  new ReactPlugin({
    port: 7000
  })
  ```

- `hostname` (default: `localhost`): The URL the variations server runs at.
  ```JS
  new ReactPlugin({
    hostname: 'mydomain.com'
  })
  ```

**Comment by nikgraf** [comment]
Agreed on both.

- `pageComponent` would also be good

**Comment by jantimon** [comment]
We might allow to change the `client.js` so someone could build a client library for his specific use case.

**Comment by jantimon** [comment]
Exclude might not be necessary as we use minimatch and could use the negative selector a little bit like grunt:

```
 // All files except for bar.js, in alpha order:
{src: ['foo/*.js', '!foo/bar.js'], dest: ...}
```

**Comment by mxstbr** [comment]
Good idea about the swappable client. :+1: Not sure how we'd facilitate swapping the `componentPreview` (prev. `pageComponent`) in the bundled version of the client though.

**Comment by nikgraf** [comment]
What we could do:

1. Allow to overwrite just `componentPreview`.
2. Allow to overwrite just `client` own client.
3. Allow to overwrite `componentPreview` & `client`. Providing both doesn't make sense, becaue if you overwrite the client you most likely build your own `componentPreview` anyway. This solution is more flexible, but I can imagine it will lead to a lot of confusion. We can help it by throwing an error of both are defined in the config.

Thoughts?

**Comment by mxstbr** [comment]
I like having the options to override both the full client and specific parts. The API needs to make that perfectly clear from the start though, but I think that's possible.

This is how I imagine you'd override the whole client:

```JS
new PluginName({
  src: 'bla',
  client: 'myNewClientBundle.js'
})
```

But you can also only override specific parts of the client like this:

```JS
new PluginName({
  src: 'bla',
  client: {
    componentPreview: 'myComponentPreview.js',
    navigation: 'myCustomNavigation.js'
  }
})
```

That would make it clear that you can override both the client and specific parts, but also that you cannot override the full client and the `componentPreview` at the same time.

**Comment by mxstbr** [comment]
Also, a question we have to answer if we want to support this feature is how do we swap out a single part of the client, do we want the compiled ES5 compatible version bundled with React or do we want the ES6 non-compiled version with `import`s and all that.

**Comment by nikgraf** [comment]
I like the API design!

**Comment by mxstbr** [comment]
New option: 

- `plugins` (default: `PlaygroundPlugin`): An array of plugins or `"default"` to 

  ```JS
    var PlaygroundPlugin = require('atrium-plugin-react-playground');
    var SourcePlugin = require('atrium-plugin-source');

    plugins: [
      new PluginName({
        src: 'components/**/*.js',
        plugins: [
         new SourcePlugin({ /* …options for the plugin here… */ }),
         new PlaygroundPlugin()
        ]
      })
    ]
  ```

**Comment by mxstbr** [comment]
The options that need to be there for launch are: `src` (done), `dest` and `plugins`. Overriding the client isn't the highest priority for the first announcement.

**Comment by mxstbr** [comment]
## Playground Plugin Options

- `port` (default: 8000): The port the playground variations server should run at.
  ```JS
  new PlaygroundPlugin({
    port: 7000
  })
  ```

- `domain` (default: `localhost`): The URL the playground variations server runs at.
  ```JS
  new PlaygroundPlugin({
    domain: 'mydomain.com'
  })
  ```

Can you think of a better name for "domain"?

**Comment by mxstbr** [comment]
New ReactPlugin option, implemented in #163:

- `variationFolderName` (default: `variations`): The name of the folder that stores the variation files.
  ```JS
  new PlaygroundPlugin({
    variationFolderName: 'examples'
  })
  ```

Any better name ideas? I'm not a big fan of `variationFolderName`.

**Comment by nikgraf** [comment]
@mxstbr Can you change default port from `8000` to something else? 8000 is heavily used from other dev envs.

**Comment by mxstbr** [comment]
Closing since this is old!
