### ISSUE TITLE
Add an example app: User Management

### ISSUE THREAD

**Issue by nikgraf** [carteb/carte-blanche#146]
A simple list which can be filtered by: name & 2 checkboxes

There is a detail view for a user + some events.

**Comment by nikgraf** [comment]
It's a bit like google contacts. this is quite independent

@busypeoples @neuling interested to help out?

**Comment by nikgraf** [comment]
how to start:

```
git checkout users

npm install
npm run example:users
```

**Comment by nikgraf** [comment]
# Pages

- [ ] UserList (has multiple UserPreview & a the AddUser component)
- [ ] UserDetail shows the avatar, firstName, lastName

OtherComponents

- [ ] UserPreview (shows the avatar, firstName, lastName)
   - clicking on a UserPreview redirects to UserDetail
- [ ] AddUser (has a form to a firstName & lastName & url to avatar)
    - every time a new user is added the form is reset

**Comment by mxstbr** [comment]
This was done in #255 and subsequent PRs!
