### ISSUE TITLE
Usage flow

### ISSUE THREAD

**Issue by mxstbr** [carteb/carte-blanche#15]
This is how I imagine the setup for the plugin works which, at the same time, is the text that will be in the README. (names dependent on https://github.com/pure-ui/react-pure-ui/issues/3)

----

# Setup

Setting up pluginname is an easy two-step process:

1. Install the plugin with `npm install --save-dev pluginname`

2. Add it to the plugins in your development webpack configuration, specifying a [glob pattern](https://github.com/isaacs/node-glob#glob-primer) to all components in the `src` option: 
  ```JS
  plugins: [
    new PluginName({
      src: 'app/**/*.react.js'
    })
  ],
  ```

That's it, now start your development environment and go to `/styleguide` to see your styleguide!

----

Questions:

- In step 1., do we include the `--save-dev`?
- In step 2, do we want to show the webpack configuration in more/less context?

**Comment by jantimon** [comment]
I like it. keep it short and simple :+1:

**Comment by nikgraf** [comment]
yes, let's include --save-dev. I always copy commands and then notice later that I forgot to add `--save-dev`.

Less context + link to an example right away.

**Comment by mxstbr** [comment]
Less context would be:

```JS
new PluginName({
  src: 'app/**/*.react.js'
})
```

I think the context is fine, but I agree with linking to an example right away!

**Comment by nikgraf** [comment]
You first suggestion looked pretty good to me :+1:

**Comment by mxstbr** [comment]
Closing since old!
