### ISSUE TITLE
Document injectTags option of the ReactPlugin

### ISSUE THREAD

**Issue by mxstbr** [carteb/carte-blanche#267]
```JS
new ReactPlugin({
  injectTags: ['<link href="…" rel="stylesheet />'],
}),
```

Injects these tags into the iframes of the rendered components. Useful for webfonts etc.

**Comment by nikgraf** [comment]
solved with: https://github.com/carteb/carte-blanche/commit/43c7208cc91dc97ad194984530d0f21f552c3706
