### ISSUE TITLE
Add CommonsChunkPlugin support

### ISSUE THREAD

**Issue by FezVrasta** [carteb/carte-blanche#285]
I'm using `react-boilerplate`, when I add `carte-blanche` and I visit `/carte-blanche` I get

```
Uncaught ReferenceError: webpackJsonp is not defined
```

How can I fix it?

**Comment by mxstbr** [comment]
That's because `react-boilerplate` uses the `CommonsChunkPlugin`. Use the `injectTags` option of the `ReactPlugin` to inject `<script src="common.js.js"></script>` (yeah, that `.js.js` is a bug…) and it _should_ work!

**Comment by FezVrasta** [comment]
Like this?

```js
    new CarteBlanche({
      componentRoot: './app/components',
      plugins: [
        new ReactPlugin({ injectTags: ['<script src="common.js.js"></script>'] }),
      ],
    }),
```

If so, it still doesn't work... actually it doesn't add the script tag.

**Comment by FezVrasta** [comment]
I just noticed that ReactPlugin injects the tag in the iframes, the problem is that the error is thrown by the Carte Blanche bundle, not by the components.

The page just don't load at all.

**Comment by mxstbr** [comment]
Ah, damn, that's a problem! Will look into it, we might have to add an `injectTags` options to the main CarteBlanche plugin.

**Comment by eddiewang** [comment]
I'm getting this error as well. What would be the best way to approach this issue?

**Comment by mxstbr** [comment]
Not yet fixed, we're on it!

**Comment by eddiewang** [comment]
Awesome - thanks. FYI I'm using: https://github.com/rangle/react-redux-starter

**Comment by mxstbr** [comment]
Done with v0.2! :tada: Now onwards to try with `react-boilerplate` again…

**Comment by FezVrasta** [comment]
Are you going to release 0.2 anytime soon? Thanks

**Comment by mxstbr** [comment]
It's released!

**Comment by FezVrasta** [comment]
Oh sorry I thought you would have added a release on GitHub.

**Comment by mxstbr** [comment]
Ah, forgot to push the tag, my bad! Thanks for reminding me, it'll be right there…

**Comment by NickMalt** [comment]
Is it work with react-boilerplate now?
