### ISSUE TITLE
Custom CSS gets overwritten

### ISSUE THREAD

**Issue by Anahkiasen** [carteb/carte-blanche#289]
I'm using the plugin as such:

```js
new CarteBlanche({
    componentRoot: './src/Components',
    files: [
        path.resolve('dist/client.css'),
    ],
}),
```

When I look at `/dist/carte-blanche/index.html` I do see the `<style>` tags with my CSS in it, in this case a basic Bootstrap:

```css
.form-control {
  display: block;
  width: 100%;
  height: 34px;
  padding: 6px 12px;
  font-size: 14px;
  line-height: 1.42857;
  // ...
```

However when I actually go into Carte Blanche and look at a component using those styles, they're nowhere to be found:

![screen shot 2016-06-03 at 15 28 27](https://cloud.githubusercontent.com/assets/1321596/15780013/defddc54-299f-11e6-9ed5-a8eb2e0fc773.png)

Inspecting CB's `<head>` also shows a good bunch of `<style>` tags but [none containing my CSS](https://gist.github.com/Anahkiasen/043a6a3d0ee6a65501e931fa8b03739f). Same thing for the `<head>` in the component's iframe

**Comment by mxstbr** [comment]
That's because the components are rendered in an iframe, which doesn't let any styles go through.

We currently don't support the `files` option for the ReactPlugin, but the `injectTags` option could be of help:

```JS
plugins: [
  new CarteBlanche({
    componentRoot: './src/Components',
    plugins: [
      new CarteBlancheReactPlugin({
        injectTags: ['<link rel="stylesheet" href="path/to/custom.css" />']
      });
    ]
  })
]
```

**Comment by Anahkiasen** [comment]
What about the `files` option of the React plugin itself, what does it do differently?

**Comment by mxstbr** [comment]
It doesn't work currently, due to the way the API is designed at the moment. That's high up on our list of bugs to fix!

**Comment by Anahkiasen** [comment]
Ok! Using `injectTags` in the meantime, can confirm that solved my issue. Can close this if you want

**Comment by mxstbr** [comment]
Awesome, thanks! We're working on it!
