### ISSUE TITLE
No `server.js` in TodoMVC example

### ISSUE THREAD

**Issue by sotojuan** [carteb/carte-blanche#297]
The `npm start` script [run a `server.js`](https://github.com/carteb/carte-blanche/blob/fbf38b5c3903141f137e3f2a8db567a6bf1b6d5b/examples/redux/todomvc/package.json#L6) file that does not exist in the directory.

**Comment by mxstbr** [comment]
Use `npm run example:redux:todomvc` from the root folder the `npm start` command is an artifact from the creation!

**Comment by sotojuan** [comment]
Thanks! That should be in the README or in the root of the examples. Maybe a good idea for a PR?

**Comment by mxstbr** [comment]
Definitely PR worthy! :+1:
