### ISSUE TITLE
/carte-blanche URL does not work

### ISSUE THREAD

**Issue by tomduncalf** [carteb/carte-blanche#302]
I tried adding carte-blanche to a simple project of mine, but when running it, http://localhost:3000/carte-blanche does not load Carte Blanche – it just loads the app instead (which does not use react-router at the minute as it's just one page)

I wonder if I need to change something in the dev server? Or is react-router a requirement perhaps? I've not had a chance to look into how Carte Blanche works or what exactly might be affecting it working in this case (I have seen it loading with a repo based on Max's boilerplate) but have pushed a stripped down version of the repo to https://github.com/tomduncalf/carte-blanche-bug if anyone is able to take a look and let me know where I might be going wrong!

Thanks

**Comment by wmertens** [comment]
Can you post your webpack configuration? Basically, the carte blanche files are generated to reside under `/carte-blanche` on your webpack-dev-server, so you need to be able to get there. If you run it on a different port, you need to go to that port.

**Comment by tomduncalf** [comment]
Sure, here it is: https://raw.githubusercontent.com/tomduncalf/carte-blanche-bug/master/webpack.config.js

`http://localhost:3000` is definitely hitting the dev server, but `http://localhost:3000/carte-blanche` just shows the same page as `/`. No doubt I have done something silly ;)

**Comment by wmertens** [comment]
you have publicPath set to `/static`, which means that the url is `http://localhost:3000/static/carte-blanche`. Try removing that, see also #304 for why it won't work :)

**Comment by tomduncalf** [comment]
Ah excellent, thank you! I'll try that out when I get home. I use `publicPath` so that my dev server JS lives in the same place as my built JS (`/static/index.js`) – is there a better way to do this? It's not a problem to use `/static` in the carte-blanche URL really

**Comment by wmertens** [comment]
No, I think using a prefix is great, carte-blanche should just fix this situation.

**Comment by tomduncalf** [comment]
Cool, I've 👍  your other issue, thanks for the help :)

**Comment by mxstbr** [comment]
Yes, definitely a bug on our side, got an idea how to fix it already though! Sorry for the troubles!

**Comment by hugobessaa** [comment]
@mxstbr any news here? Real blocker for us. I've got an idea on how to do this too.

**Comment by mxstbr** [comment]
Not as of yet, I'm afraid. If you want to take a look that'd be much appreciate, feel free to submit a WIP Pull Request and we can do it together!

(Also, joining the chat might be good for discussions: https://gitter.im/carteb/carte-blanche)
