### ISSUE TITLE
CSS issues?

### ISSUE THREAD

**Issue by christianalfoni** [carteb/carte-blanche#303]
Hi there,

Really great project!

Running this project there seems to be CSS issues with it? Notice that the content of the modal is not taking up all the space, the right scrollbar there.

There is no save button, so can not create examples of my components?

![screen shot 2016-06-07 at 10 41 08](https://cloud.githubusercontent.com/assets/3956929/15851355/b077403c-2c9c-11e6-80c1-e69b686e30fd.png)

**Comment by wmertens** [comment]
Seeing the same thing, also the sidebar does not scroll if there are too many components.

The props are auto-save though, so that works.

**Comment by mxstbr** [comment]
Dang, @nikgraf that ones for you I think!

@christianalfoni what browser/device are you on? 

> The props are auto-save though, so that works.

We should add a "Saving…"/"Saved!" indicator for the autosave functionality!

**Comment by christianalfoni** [comment]
Using latest Chrome.

would suggest adding a bit opacity to the modal so that you can see the component changing in the background. Makes it a little bit more intuitive maybe. 

I think I was confused by the demo picture where it looked like you were adding multiple components to "Core" and "edge case". Maybe use an example with a simple button where you say "primary", "secondary" etc. The list just threw me off a bit, so was looking for a way to add and save multiple components. Anyways... it might be me being stupid :)

I can send you a picture of our project with some buttons to suggest changing it.

**Comment by mxstbr** [comment]
Yeah, the UI/UX of the thing is by far not perfect yet. See #246 and #259 for more information.

**Comment by nikgraf** [comment]
@christianalfoni I just tried to run it. Checkout out the branch and did `npm install` & `npm start`, but id didn't work. Anything else I need to do?

I get a couple of these:
```
ERROR in ./common/IconSVG/index.js
Module not found: Error: Cannot resolve module 'ducky-assets/vector_graphics/activities/act_consumption_01_repair.svg' in /path/to/project/ducky-components/common/IconSVG
 @ ./common/IconSVG/index.js 19:33-113
```

One thing I noticed is that you guys use React 0.14.8. In theory we could package React into the client bundle and only use your React version for the iFrame. This is not the case right now, which might break the app.

**Comment by christianalfoni** [comment]
Be sure to check out the `cartheblanch` branch... typo there, hehe.

Also I have pushed the ducky-assets in there now, so it is part of the project. ACtually a hidden repo... but nothing secret there

**Comment by nikgraf** [comment]
@christianalfoni works now, thx

**Comment by nikgraf** [comment]
@christianalfoni Just discovered the issue: right now we don't get out the css from ExtractTextPlugin inside the iFrame. We need to fix this on our side. Hopefully in the next couple days. I got it working using the raw style loader. For some reason the icons inside an ActionButton are missing while working fine on the `/` root page. Any ideas?

<img width="1278" alt="screen shot 2016-06-07 at 14 53 51" src="https://cloud.githubusercontent.com/assets/223045/15858656/e2be8b16-2cc1-11e6-8be6-c304346f71c2.png">
<img width="816" alt="screen shot 2016-06-07 at 14 58 06" src="https://cloud.githubusercontent.com/assets/223045/15858657/e2c220b4-2cc1-11e6-94ca-3e5ae8a987c4.png">

**Comment by christianalfoni** [comment]
Great stuff, thanks :)

We do not need to use extract plugin in development anyways, so I can turn that off.

About the images it might be because we use a relative path to get them, but should absolute path. So it tries to find image on `/carte-blanche/someimage.png`, but it is located on : `/someimage.png`... Let me look into it and let you know :)

**Comment by christianalfoni** [comment]
Ah no, it is some fonts we load in our index.html file

**Comment by christianalfoni** [comment]
Hm, is there any strategy for loading stylesheets in the carte-blanche dashboard?

**Comment by christianalfoni** [comment]
I can write a stylesheet loader plugin maybe :)

**Comment by nikgraf** [comment]
@christianalfoni yep there is a `files` option as well as the `injectTags` option for the React plugin. Still need to document them 😄 

https://github.com/carteb/carte-blanche/blob/master/examples/redux/todomvc/webpack.config.babel.js#L29-L33

https://github.com/carteb/carte-blanche/blob/master/examples/users/webpack.dev.babel.js#L35-L37

**Comment by christianalfoni** [comment]
Sweet! though... hm:

```js
    ReactPlugin = require('carte-blanche-react-plugin');

...

        new CarteBlanche({
            componentRoot: './common',
            plugins: [
                new ReactPlugin({
                    injectTags: [
                        '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">',
                    ]
                })
            ]
        }),
```

Kan not see the tag is injected looking at the source of the html, and no icon there, hm hm

**Comment by nikgraf** [comment]
Did you push? I can double check what's going on 🙌

**Comment by christianalfoni** [comment]
Pushed, awesome, big thanks :)

**Comment by nikgraf** [comment]
@christianalfoni Just checkout out your version. The tag actually was injected, but in the body. I moved them into the head with this PR https://github.com/carteb/carte-blanche/pull/310, but I don't think it makes a difference. May it be that it was the wrong CSS file?

<img width="369" alt="screen shot 2016-06-08 at 08 24 12" src="https://cloud.githubusercontent.com/assets/223045/15884900/aff82dd0-2d53-11e6-8b5a-396b519a3e98.png">

In the css file I could only find classes like: `zmdi-battery`

**Comment by nikgraf** [comment]
@christianalfoni Max already merged a PR to make the left sidebar scrollable 🙌

**Comment by christianalfoni** [comment]
Can you have <link> tags in the body? Thought they were required in the head tag... hm hm... anyways, big thanks. Will try it out next week again. Big thanks for all your help @nikgraf !

**Comment by mxstbr** [comment]
> Can you have tags in the body? 

It's HTML, you can have everything everywhere. :grin:

**Comment by christianalfoni** [comment]
Aha, in HTML4: “This element defines a link. Unlike A, it may only appear in the HEAD section of a document, although it may appear any number of times.” HTML5 it is okay :) Though yes, bad practice I would suggest as styles are not added before body renders... of course depending on scenario. Anyways, good to know :)

**Comment by mxstbr** [comment]
Absolutely agreed, very bad practice! It's fixed now anyway, that was just my quickly-finish-this-before-launch-coding :grin:
