### ISSUE TITLE
Add autosave indicator

### ISSUE THREAD

**Issue by mxstbr** [carteb/carte-blanche#305]
We should have an indicator (similar to the Medium editor) that tells people when we're autosaving/that we've autosaved.

**Comment by nikgraf** [comment]
@mxstbr I gave this a bit more thought: I suggest we show the indicator right away and wait 500ms for fading out. This way it doesn't blink up for every character you type.

I suggest to have a green little box saying `Saved …` with position absolute at the top/right.

**Comment by mxstbr** [comment]
Sure

**Comment by lithin** [comment]
We could throttle it instead? I'll see how complicated that would be :)

**Comment by mxstbr** [comment]
Not much, I think.

If you want to give this a shot, all the relevant code is in `plugins/react/components/PlaygroundList.js`, specifically you'd want to look at adding another property to the state and the `changeVariation` and `persistVariation` methods!

**Comment by lithin** [comment]
Awesome thanks!

**Comment by nikgraf** [comment]
done by @lithin 🙌
