### ISSUE TITLE
Support for making libraries

### ISSUE THREAD

**Issue by tmc** [carteb/carte-blanche#321]
If this is set as the output library name:
``` 
module.exports = {
  output: {
    library: '[name]',
  },
```

user-bundle.js gets generated like so:
```
var CarteBlanche [0] =
/******/ (function(modules) { // webpackBootstrap
```
(which is invalid)

**Comment by mxstbr** [comment]
> `output library`

Are you making a library?

I think that's a usecase we haven't accounted for so far, would you mind adding an example to the repo with your webpack config?

**Comment by tmc** [comment]
@mxstbr example config here: https://github.com/tmc/cb-test

**Comment by mxstbr** [comment]
Thanks, taking a look!
