### ISSUE TITLE
Use source of faker.js instead of "compiled" one.

### ISSUE THREAD

**Issue by FezVrasta** [carteb/carte-blanche#336]
This warning comes out when you use Carte Blanche, it's a bit annoying, maybe suppress it or do what it says?

```
WARNING in ./~/faker/build/build/faker.js
Critical dependencies:
1:436-443 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/faker/build/build/faker.js 1:436-443
```

**Comment by nikgraf** [comment]
Yeah, we had troubles when importing faker directly, but didn't investigate much.

@FezVrasta interested to investigate here?

**Comment by FezVrasta** [comment]
I'll look at it tomorrow probably.
