### ISSUE TITLE
Cannot find module carte-blanche-react-plugin

### ISSUE THREAD

**Issue by lithin** [carteb/carte-blanche#343]
When adding `const ReactPlugin = require('carte-blanche-react-plugin');` to my webpack config, webpack doesn't build because it "Cannot find module carte-blanche-react-plugin". Node modules are installed properly, `carte-blanche-react-plugin` is installed in `./node_modules/carte-blanche/node_modules`.

After `npm i -s carte-blanche-react-plugin`, everything works as expected.

This seems to be an issue only on certain devices - could be maybe some local settings? Has anyone had similar issues?

**Comment by mxstbr** [comment]
What's your `npm` version? I think this changed with the recent v3 update, but I'm not 100% sure.

**Comment by lithin** [comment]
You're right! Sorry didn't realise I'm still using an ancient version!

**Comment by mxstbr** [comment]
No worries, glad to know it's working now! :+1:
