### ISSUE TITLE
traverseParentPath(...) error when selecting a component

### ISSUE THREAD

**Issue by bytewiz** [carteb/carte-blanche#348]
Added one component to and then visited th carte-blanche but when selecting the component and the pop up shows this follow error is thrown:

``
Generating metadata failed Error: traverseParentPath(...): Cannot traverse from and to the same ID, ''.(…)(anonymous function) @ index.js:301
``

<img width="1438" alt="screen shot 2016-06-13 at 23 10 44" src="https://cloud.githubusercontent.com/assets/16811871/16023245/37a2a9ce-31bc-11e6-98a2-1700604a2997.png">

**Comment by mxstbr** [comment]
What does your component and layout of the component folder look like?

**Comment by bytewiz** [comment]
The App component which imports the List component
<img width="777" alt="screen shot 2016-06-13 at 23 45 00" src="https://cloud.githubusercontent.com/assets/16811871/16024205/e7b2b396-31c0-11e6-81d8-bdf604651327.png">


The List component.
<img width="770" alt="screen shot 2016-06-13 at 23 43 01" src="https://cloud.githubusercontent.com/assets/16811871/16024178/b1391d00-31c0-11e6-9ee3-bd94c7344062.png">

**Comment by bytewiz** [comment]
@mxstbr any idea why this happens?

**Comment by mxstbr** [comment]
I think `<div>this.props.firstName</div>` is invalid JSX syntax, it should be `<div>{ this.props.firstName }</div>`, which might be the problem?

**Comment by bytewiz** [comment]
Lol,.. my bad, let's close this one :-)

**Comment by mxstbr** [comment]
Hmm, not quite sure to be honest. Could you provide a contained repro case as a git repo? Then I'll take a look!

**Comment by skayred** [comment]
Can confirm the same behavour, see the sample project
[https://github.com/skayred/carte-blanche-hello-world](url)

I can provide any additional info if needed

**Comment by bytewiz** [comment]
@skayred I can confirm the exact same behaviour in the sample project. same error.

**Comment by mxstbr** [comment]
Thanks for the repro case, will look into it!

**Comment by ewnd9** [comment]
`react@0.14` is the issue here, it's working with the latest react https://github.com/ewnd9/carte-blanche-hello-world

**Comment by mxstbr** [comment]
Hah, awesome, thanks for digging in @ewnd9, much appreciated! :+1:

**Comment by ewnd9** [comment]
@mxstbr thanks for the project :clap: By the way, shouldn't be the `react@15` requirement mentioned in the readme?

**Comment by mxstbr** [comment]
> By the way, shouldn't be the react@15 requirement mentioned in the readme?

That sounds like a very reasonable idea, would you mind submitting a PR adding that? :pray:

**Comment by ewnd9** [comment]
@mxstbr done https://github.com/carteb/carte-blanche/pull/356
