### ISSUE TITLE
components with lower case filename not recognized

### ISSUE THREAD

**Issue by FredericHeem** [carteb/carte-blanche#359]
Is it intended that components must start with an upper case as the first character of the filename ?

**Comment by mxstbr** [comment]
Yes, the default filtering regex (`/(\/[A-Z][a-zA-Z]*.?\/index|\/[A-Z][a-zA-Z]*)\.(jsx?|es6|react\.jsx?)$/`) does that.

You can easily adapt that though, this _should_ work:

```JS
new CarteBlanche({
  filter: /(\/[A-Z][a-zA-Z]*.?\/index|\/[a-zA-Z]*)\.(jsx?|es6|react\.jsx?)$/
})
```
