### ISSUE TITLE
Add docs for /examples

### ISSUE THREAD

**Issue by kevinSuttle** [carteb/carte-blanche#367]
e.g. There are no docs for running the server other than 

> now start your development environment 

Webpack dev server gives me `cannot Get /carte-blanche`

**Comment by mxstbr** [comment]
Which server are you using? Express.js?

**Comment by kevinSuttle** [comment]
Webpack dev server, which uses Express under the hood. https://github.com/webpack/webpack-dev-server/blob/master/package.json#L12

**Comment by mxstbr** [comment]
Wait, are you running the examples of this repo?

**Comment by kevinSuttle** [comment]
Yeah...

**Comment by mxstbr** [comment]
`npm run example:directoryname` runs the examples, e.g. `npm run example:dev`. 

What kind of docs do you expect for the examples?

**Comment by kevinSuttle** [comment]
What you just posted is a great start. :)

**Comment by mxstbr** [comment]
They're mostly meant for us maintainers to help develop for different setups! They mostly aren't very exciting :grin:

**Comment by kevinSuttle** [comment]
Fair enough. It's just hard to know how to get CB set up and running on a given server.

**Comment by mxstbr** [comment]
Shouldn't be much more difficult than

```JS
new CarteBlanche({
  componentRoot
});
```

in your webpack configuration. If it doesn't work with a specific server setup please submit an issue for that!
