### ISSUE TITLE
Change CSS of iframe

### ISSUE THREAD

**Issue by simeg** [carteb/carte-blanche#373]
I'd like to change the background color of the iframe that's containing my component, is there any way to do this in the current version?

**Comment by mxstbr** [comment]
The `files` option of the ReactPlugin should do it! https://github.com/carteb/carte-blanche#reactplugin-options

**Comment by nikgraf** [comment]
@simeg did you get it to work?

**Comment by simeg** [comment]
Thanks for the replies guys. but I have not got it to work yet. The file doesn't seem to load, I didn't have too much time to debug it. I'll keep you posted.
