### ISSUE TITLE
Can't install carte-blanche

### ISSUE THREAD

**Issue by acierto** [carteb/carte-blanche#377]
I have very strange unmet peer dependency on itself by installing carte-blanche ` npm install --save-dev carte-blanche`, used react version is: "15.2.1"
<img width="339" alt="screen shot 2016-07-13 at 21 41 07" src="https://cloud.githubusercontent.com/assets/2265094/16817322/946db08e-4942-11e6-958d-80e2dbbd6c91.png">

**Comment by mxstbr** [comment]
Oh what, that's really weird. Let me take a look

**Comment by mxstbr** [comment]
Fixed in `carte-blanche@0.3.1`, sorry about that!
