### ISSUE TITLE
Uncaught SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by necolas** [carteb/carte-blanche#378]
I was looking into using storybook or carte-blanche to create a UI explorer for react-native-web. I followed the README instructions and added this to my webpack config:

``` js
new CarteBlanche({
  componentRoot: path.join(__dirname, '../src/components'),
  filter: /index.js$/
}),
```

But navigating to any example component produces this error:

``` js
Uncaught SyntaxError: Unexpected token u in JSON at position 0
```

**Comment by mxstbr** [comment]
Holy cow that's awesome! Do you have a repro somewhere so I can take a look at this specific bug?

(We don't have support for a non-editable mode at the moment, but if you give me a day I'll get that implemented!)

**Comment by necolas** [comment]
Oh, having the examples be editable is fine. It would be something used during development as much as for external consumption.

To repro:

1. git clone react-native-web
2. `npm install carte-blanche`
3. Add that code block to `examples/webpack.config.js`
4. `npm run examples`

**Comment by mxstbr** [comment]
Will take a look tomorrow!

**Comment by LeZuse** [comment]
Also encountered this one. I made a workaround by fixing https://github.com/carteb/carte-blanche/blob/0cedc40b10b788508a255dc9d854c517c68ce24f/plugins/react/frontend/index.js#L24 with this:
```
basePath={JSON.parse(pluginData && pluginData.basePath || '{}')}
```

But the the root cause is probably deeper than that.

**Comment by nikgraf** [comment]
Just tried, I even get an earlier error … need to take a closer look at another time.

<img width="545" alt="screen shot 2016-07-17 at 08 51 59" src="https://cloud.githubusercontent.com/assets/223045/16899218/d61aa5f8-4bfb-11e6-9eed-977a96ddde5c.png">

**Comment by nikgraf** [comment]
@LeZuse do you have an example repo?

**Comment by LeZuse** [comment]
@nikgraf I will try to make an isolated repro and will get back to you.

**Comment by thebuilder** [comment]
@nikgraf I'm getting the same error - Seem to fail while parsing the Component data:

It's calling http://localhost:8082/variations/src/components/Footer/Footer.js, which returns:
```
{"data":{}}
```
