### ISSUE TITLE
index.html: Wrong bundle/css paths

### ISSUE THREAD

**Issue by oreqizer** [carteb/carte-blanche#394]
<img width="462" alt="screen shot 2016-11-04 at 13 56 21" src="https://cloud.githubusercontent.com/assets/11172408/20006154/96abfcd6-a296-11e6-886d-1288a368bcc3.png">

My config:
```javascript
new CarteBlanche({
    componentRoot: path.join(__dirname, "common/libComponents"),
})
```

**Comment by wmertens** [comment]
@oreqizer componentRoot is where CB finds the components, not where it serves them from.

**Comment by wmertens** [comment]
You want

```
dest (default: 'carte-blanche'): Change the location of your Carte Blanche. Needs to be a path.

  plugins: [
    new CarteBlanche({
      componentRoot: 'src/components',
      dest: 'components'
    })
  ]
```
